package org.jlab.icalibrate.wizard.page;

import org.jlab.icalibrate.model.CreateNewDatasetParameters;
import org.jlab.icalibrate.model.IonChamber;
import org.jlab.icalibrate.wizard.Wizard;
import org.jlab.icalibrate.wizard.WizardPage;

/**
 * Prompts the operator to confirm the data gathering options are correct before starting the process.
 *
 * @author ryans
 */
public class ReviewPage extends WizardPage<CreateNewDatasetParameters> {

    /**
     * Create a new ReviewPage
     *
     * @param wizard The wizard
     */
    public ReviewPage(Wizard<CreateNewDatasetParameters> wizard) {
        super(wizard, "Review");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hallPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        hallLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        laserLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        targetLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        noteLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ionChamberListLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        minAttenuatorLabel = new javax.swing.JLabel();
        maxAttenuatorLabel = new javax.swing.JLabel();
        numberOfStepsLabel = new javax.swing.JLabel();
        settleSecondsLabel = new javax.swing.JLabel();
        samplesPerStepLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        stepSizeLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        durationSecondsLabel = new javax.swing.JLabel();

        hallPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Hall:");

        hallLabel.setText("A");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Laser:");

        laserLabel.setText("A");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Target:");

        targetLabel.setText("Carbon");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Pass:");

        passLabel.setText("5.5");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Note:");

        noteLabel.setText("Comments go here");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ion Chambers");

        ionChamberListLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jScrollPane1.setViewportView(ionChamberListLabel);

        javax.swing.GroupLayout hallPanelLayout = new javax.swing.GroupLayout(hallPanel);
        hallPanel.setLayout(hallPanelLayout);
        hallPanelLayout.setHorizontalGroup(
            hallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hallPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, hallPanelLayout.createSequentialGroup()
                        .addGroup(hallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addGroup(hallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hallLabel)
                            .addComponent(laserLabel)
                            .addComponent(targetLabel)
                            .addComponent(passLabel)
                            .addComponent(noteLabel))
                        .addGap(0, 61, Short.MAX_VALUE)))
                .addContainerGap())
        );
        hallPanelLayout.setVerticalGroup(
            hallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hallPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(hallLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(laserLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(targetLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(passLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(noteLabel))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Min Attenuator:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Max Attenuator:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("# Attenuator Steps:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Step Settle Time (Seconds):");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("# Samples Per Step:");

        minAttenuatorLabel.setText("0");

        maxAttenuatorLabel.setText("100");

        numberOfStepsLabel.setText("10");

        settleSecondsLabel.setText("2");

        samplesPerStepLabel.setText("3");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Step Size:");

        stepSizeLabel.setText("10");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Duration (Seconds):");

        durationSecondsLabel.setText("50");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel21)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minAttenuatorLabel)
                    .addComponent(maxAttenuatorLabel)
                    .addComponent(numberOfStepsLabel)
                    .addComponent(settleSecondsLabel)
                    .addComponent(samplesPerStepLabel)
                    .addComponent(stepSizeLabel)
                    .addComponent(durationSecondsLabel))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(minAttenuatorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(maxAttenuatorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(numberOfStepsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(settleSecondsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(samplesPerStepLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(stepSizeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(durationSecondsLabel))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hallPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hallPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel durationSecondsLabel;
    private javax.swing.JLabel hallLabel;
    private javax.swing.JPanel hallPanel;
    private javax.swing.JLabel ionChamberListLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel laserLabel;
    private javax.swing.JLabel maxAttenuatorLabel;
    private javax.swing.JLabel minAttenuatorLabel;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JLabel numberOfStepsLabel;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel samplesPerStepLabel;
    private javax.swing.JLabel settleSecondsLabel;
    private javax.swing.JLabel stepSizeLabel;
    private javax.swing.JLabel targetLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void enter() {
        CreateNewDatasetParameters params = getParameters();

        hallLabel.setText(params.getHall().name());
        laserLabel.setText(params.getLaser().name());
        targetLabel.setText(params.getTarget());
        passLabel.setText(params.getPass());
        noteLabel.setText(params.getNote());

        minAttenuatorLabel.setText(String.valueOf(params.getMinAttenuator()));
        maxAttenuatorLabel.setText(String.valueOf(params.getMaxAttenuator()));
        numberOfStepsLabel.setText(String.valueOf(params.getNumberOfSteps()));
        settleSecondsLabel.setText(String.valueOf(params.getSettleSeconds()));
        samplesPerStepLabel.setText(String.valueOf(params.getSamplesPerStep()));

        stepSizeLabel.setText(String.valueOf(params.computeStepSize()));
        durationSecondsLabel.setText(String.valueOf(params.computeDurationSeconds()));
        
        String icListStr = "<html>";
        
        for(IonChamber ic: params.getIonChamberList()) {
            icListStr = icListStr + ic.getFriendlyNameOrEpicsName() + "<br/>";
        }
        
        icListStr = icListStr + "</html>";
        
        ionChamberListLabel.setText(icListStr);
    }

    @Override
    public void leave() {
    }

    @Override
    public void reset() {
    }
}
