package org.jlab.icalibrate.wizard;

import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.jlab.icalibrate.exception.ValidationException;
import org.jlab.icalibrate.swing.dialog.ModalWaitDialog;

/**
 * A Swing GUI wizard dialog.
 *
 * @author ryans
 * @param <T> The type of Shared Parameter object
 */
public class Wizard<T> extends ModalWaitDialog {

    private List<WizardPage> pageList;
    private final T params;
    private int pageIndex = 0;

    /**
     * Create a new Wizard.
     *
     * @param parent The parent frame
     * @param params The parameters
     * @param finishAction The action to perform on wizard completion
     */
    public Wizard(Frame parent, T params, Action finishAction) {
        super(parent, true);
        this.params = params;
        initComponents();
        finishButton.setAction(new AbstractAction() {

            {
                this.putValue(Action.NAME, finishAction.getValue(Action.NAME));
            }

            @Override
            public void actionPerformed(ActionEvent e) {
                Wizard.this.dispose();
                finishAction.actionPerformed(e);
            }
        });
    }

    /**
     * Set the WizardPage list.
     * 
     * @param pageList The wizard page list
     */
    public void setPageList(List<WizardPage> pageList) {
        this.pageList = pageList;
        initPageList();
    }

    /**
     * Resets the wizard. This is called each time before launching the wizard. This method results
     * in reset being called on each wizard page.
     */
    public void reset() {
        setSelectedIndex(0);

        for (WizardPage page : pageList) {
            page.reset();
        }
    }

    private void initPageList() {

        pagePanel.removeAll();
        outlineStack.removeAll();

        int i = 1;
        for (WizardPage page : pageList) {
            pagePanel.add(page, page.getTitle());
            outlineStack.add(new JLabel(i++ + ". " + page.getTitle()));
        }

        setSelectedIndex(0);
    }

    private void setSelectedIndex(int pageIndex) {
        this.pageIndex = pageIndex;

        WizardPage page = pageList.get(pageIndex);

        for (Component c : outlineStack.getComponents()) {
            c.setFont(new Font("Tahoma", 0, 11));
        }

        outlineStack.getComponents()[pageIndex].setFont(new Font("Tahoma", 1, 11));
        pageTitleLabel.setText(page.getTitle());

        previousButton.setEnabled(pageIndex > 0);

        if (pageIndex >= pageList.size() - 1) {
            nextButton.setEnabled(false);
            finishButton.setEnabled(true);
        } else {
            nextButton.setEnabled(true);
            finishButton.setEnabled(false);
        }

        ((CardLayout) pagePanel.getLayout()).show(pagePanel, page.getTitle());

        page.enter();
    }

    /**
     * Try to leave the current page.
     *
     * @return true if successful, false otherwise
     */
    private boolean leave() {
        boolean success = true;

        WizardPage page = pageList.get(pageIndex);

        try {
            page.leave();
        } catch (ValidationException e) {
            success = false;

            String title = "Unacceptable Input";
            String message = e.getMessage();

            JOptionPane.showMessageDialog(this, message, title, JOptionPane.ERROR_MESSAGE);
        }

        return success;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outlinePanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        outlineStack = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        pagePanel = new javax.swing.JPanel();
        finishButton = new javax.swing.JButton();
        pageTitleLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 400));
        setPreferredSize(new java.awt.Dimension(700, 400));
        setResizable(false);

        outlinePanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Steps");

        outlineStack.setBackground(new java.awt.Color(255, 255, 255));
        outlineStack.setLayout(new javax.swing.BoxLayout(outlineStack, javax.swing.BoxLayout.PAGE_AXIS));

        javax.swing.GroupLayout outlinePanelLayout = new javax.swing.GroupLayout(outlinePanel);
        outlinePanel.setLayout(outlinePanelLayout);
        outlinePanelLayout.setHorizontalGroup(
            outlinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outlinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(outlinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(outlineStack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        outlinePanelLayout.setVerticalGroup(
            outlinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outlinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outlineStack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        previousButton.setText("Previous");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        pagePanel.setLayout(new java.awt.CardLayout());

        finishButton.setText("Finish");
        finishButton.setEnabled(false);
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        pageTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pageTitleLabel.setText("Step Title");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(outlinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 227, Short.MAX_VALUE)
                        .addComponent(previousButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finishButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addComponent(jSeparator2)
                    .addComponent(pageTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pageTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(nextButton)
                    .addComponent(previousButton)
                    .addComponent(finishButton))
                .addContainerGap())
            .addComponent(outlinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        if (pageIndex < (pageList.size() - 1)) {

            boolean success = leave();

            if (success) {
                setSelectedIndex(pageIndex + 1);
            }
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        if (pageIndex > 0) {

            boolean success = leave();

            if (success) {
                setSelectedIndex(pageIndex - 1);
            }
        }
    }//GEN-LAST:event_previousButtonActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        dispose();
    }//GEN-LAST:event_finishButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton finishButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton nextButton;
    private javax.swing.JPanel outlinePanel;
    private javax.swing.JPanel outlineStack;
    private javax.swing.JPanel pagePanel;
    private javax.swing.JLabel pageTitleLabel;
    private javax.swing.JButton previousButton;
    // End of variables declaration//GEN-END:variables

    /**
     * Return the shared parameters.
     * 
     * @return The parameters
     */
    public T getParameters() {
        return params;
    }
}
